name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test-getversion-job:
    runs-on: ubuntu-latest
      step-one:
        name: Checkout code
        uses: actions/checkout@v3

      step-two:
        name: Get Version from Tag
        id: getversion
        uses: wayne-mj/getversion@v1.3

      step-three:
        name: Use release_version in workflow
        run: echo "The extracted release_version is ${{ steps.getversion.outputs.release_version }}"